HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 13 May 2018 13:01:07 GMT
Link: <https://api.github.com/search/issues?q=repo%3Achannelcat%2Fsanic+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Achannelcat%2Fsanic+type%3Aissue+state%3Aclosed&page=14>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CDDD:4F42:44DE76A:8AC0667:5AF83713
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 21
X-Ratelimit-Reset: 1526216518
X-Runtime-Rack: 0.327345
X-Xss-Protection: 1; mode=block

8000
{"total_count":407,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/channelcat/sanic/issues/1213","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1213/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1213/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1213/events","html_url":"https://github.com/channelcat/sanic/issues/1213","id":319800356,"number":1213,"title":"Post file and form data, can't get the form data in unit test","user":{"login":"pushiqiang","id":13058977,"avatar_url":"https://avatars3.githubusercontent.com/u/13058977?v=4","gravatar_id":"","url":"https://api.github.com/users/pushiqiang","html_url":"https://github.com/pushiqiang","followers_url":"https://api.github.com/users/pushiqiang/followers","following_url":"https://api.github.com/users/pushiqiang/following{/other_user}","gists_url":"https://api.github.com/users/pushiqiang/gists{/gist_id}","starred_url":"https://api.github.com/users/pushiqiang/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pushiqiang/subscriptions","organizations_url":"https://api.github.com/users/pushiqiang/orgs","repos_url":"https://api.github.com/users/pushiqiang/repos","events_url":"https://api.github.com/users/pushiqiang/events{/privacy}","received_events_url":"https://api.github.com/users/pushiqiang/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-03T06:26:20Z","updated_at":"2018-05-08T06:22:09Z","closed_at":"2018-05-08T06:21:56Z","author_association":"NONE","body":"I post file and form dataï¼Œbut in the unit test I can only get the file, I can't get the form data\r\n\r\n```\r\n        image_path = os.path.join(os.path.dirname(\r\n            os.path.abspath(__file__)), 'test.jpg')\r\n\r\n        form_data = FormData()\r\n        form_data.add_field('file', open(image_path, 'rb'))\r\n        form_data.add_field('name',  'test')\r\n\r\n        resp = await self.client.post(self.url, data=form_data)\r\n```\r\nor\r\n```\r\n        form_data = {'file': open(image_path, 'rb'),  'name': 'test'}\r\n```\r\nI can get file by request.files,but cant not get name by request.form or request.json\r\n\r\nWho  can  help  me?\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1208","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1208/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1208/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1208/events","html_url":"https://github.com/channelcat/sanic/issues/1208","id":318183843,"number":1208,"title":"Error related to class based views","user":{"login":"levismiller","id":1817116,"avatar_url":"https://avatars0.githubusercontent.com/u/1817116?v=4","gravatar_id":"","url":"https://api.github.com/users/levismiller","html_url":"https://github.com/levismiller","followers_url":"https://api.github.com/users/levismiller/followers","following_url":"https://api.github.com/users/levismiller/following{/other_user}","gists_url":"https://api.github.com/users/levismiller/gists{/gist_id}","starred_url":"https://api.github.com/users/levismiller/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/levismiller/subscriptions","organizations_url":"https://api.github.com/users/levismiller/orgs","repos_url":"https://api.github.com/users/levismiller/repos","events_url":"https://api.github.com/users/levismiller/events{/privacy}","received_events_url":"https://api.github.com/users/levismiller/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-26T20:24:33Z","updated_at":"2018-04-26T20:59:34Z","closed_at":"2018-04-26T20:59:34Z","author_association":"NONE","body":"Using the following code sample from docs page but I get an error in the Router at startup. \r\n\r\nclass SimpleView(HTTPMethodView):\r\n  def get(self, request):\r\n      return text('I am get method')\r\n  def post(self, request):\r\n      return text('I am post method')\r\n  def put(self, request):\r\n      return text('I am put method')\r\n  def patch(self, request):\r\n      return text('I am patch method')\r\n  def delete(self, request):\r\n      return text('I am delete method')\r\n\r\n**app.add_route(SimpleView.as_view(), '/')**\r\n\r\nSeeing the following error:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/app.py\", line 546, in handle_request\r\n    handler, args, kwargs, uri = self.router.get(request)\r\n  File \"/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/router.py\", line 343, in get\r\n    return self._get(request.path, request.method, '')\r\n  File \"/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/router.py\", line 397, in _get\r\n    route_handler = route.handler\r\nAttributeError: 'Route' object has no attribute 'handler'\r\n\r\nNoticed on line 257 in router.py in the call to Route() handler seems to be missing from the namedtuple above but I am new to the framework and don't fully understand what is going on so this may not be helpful.\r\n\r\n        if route:\r\n            route = merge_route(route, methods, handler)\r\n        else:\r\n            # route = Route(['view', 'methods', 'pattern', 'parameters', 'name', 'uri')\r\n            route = Route(handler=handler, methods=methods, pattern=pattern,\r\n                parameters=parameters, name=handler_name, uri=uri)\r\n\r\nRoute = namedtuple(\r\n    'Route',\r\n    ['view', 'methods', 'pattern', 'parameters', 'name', 'uri'])\r\n\r\n\r\nHere is a pip freeze:\r\naiofiles==0.3.2\r\ncertifi==2018.4.16\r\nchardet==3.0.4\r\nhttptools==0.0.11\r\nidna==2.6\r\nprotobuf==3.5.2.post1\r\nrequests==2.18.4\r\nsanic==0.7.0\r\nsix==1.11.0\r\nujson==1.35\r\nurllib3==1.22\r\nuvloop==0.9.1\r\nwebsockets==4.0.1\r\nwget==3.2","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1204","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1204/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1204/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1204/events","html_url":"https://github.com/channelcat/sanic/issues/1204","id":317169539,"number":1204,"title":"Debian 9 problem","user":{"login":"labbit","id":8208813,"avatar_url":"https://avatars0.githubusercontent.com/u/8208813?v=4","gravatar_id":"","url":"https://api.github.com/users/labbit","html_url":"https://github.com/labbit","followers_url":"https://api.github.com/users/labbit/followers","following_url":"https://api.github.com/users/labbit/following{/other_user}","gists_url":"https://api.github.com/users/labbit/gists{/gist_id}","starred_url":"https://api.github.com/users/labbit/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/labbit/subscriptions","organizations_url":"https://api.github.com/users/labbit/orgs","repos_url":"https://api.github.com/users/labbit/repos","events_url":"https://api.github.com/users/labbit/events{/privacy}","received_events_url":"https://api.github.com/users/labbit/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-24T10:42:44Z","updated_at":"2018-04-24T14:12:51Z","closed_at":"2018-04-24T14:12:51Z","author_association":"NONE","body":"LXC woth Debian 9, install from git-repo :\r\n\r\n```\r\nar: `u' modifier ignored since `D' is the default (see `U')\r\nuvloop/loop.c:20:20: fatal error: Python.h: No such file or directory\r\n #include \"Python.h\"\r\n                    ^\r\ncompilation terminated.\r\nerror: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\r\n\r\n```","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1203","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1203/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1203/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1203/events","html_url":"https://github.com/channelcat/sanic/issues/1203","id":317166098,"number":1203,"title":"Problem in Transpose of data frame from R","user":{"login":"sunbarve","id":17616433,"avatar_url":"https://avatars2.githubusercontent.com/u/17616433?v=4","gravatar_id":"","url":"https://api.github.com/users/sunbarve","html_url":"https://github.com/sunbarve","followers_url":"https://api.github.com/users/sunbarve/followers","following_url":"https://api.github.com/users/sunbarve/following{/other_user}","gists_url":"https://api.github.com/users/sunbarve/gists{/gist_id}","starred_url":"https://api.github.com/users/sunbarve/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sunbarve/subscriptions","organizations_url":"https://api.github.com/users/sunbarve/orgs","repos_url":"https://api.github.com/users/sunbarve/repos","events_url":"https://api.github.com/users/sunbarve/events{/privacy}","received_events_url":"https://api.github.com/users/sunbarve/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-04-24T10:32:06Z","updated_at":"2018-04-24T12:46:02Z","closed_at":"2018-04-24T12:46:02Z","author_association":"NONE","body":"I am trying to transpose data frame but facing this issue using R\r\n**pred_data <- data.frame(r1=names(personal_details), t(personal_details))**\r\n\r\n**Error** :  in if (inherits(X[[j]], \"data.frame\") && ncol(xj) > 1L) X[[j]] <- as.matrix(X[[j]]) :    missing value where TRUE/FALSE needed****","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1193","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1193/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1193/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1193/events","html_url":"https://github.com/channelcat/sanic/issues/1193","id":314704329,"number":1193,"title":"A problem from Update File to Sanic Server","user":{"login":"AberSheeran","id":25364828,"avatar_url":"https://avatars3.githubusercontent.com/u/25364828?v=4","gravatar_id":"","url":"https://api.github.com/users/AberSheeran","html_url":"https://github.com/AberSheeran","followers_url":"https://api.github.com/users/AberSheeran/followers","following_url":"https://api.github.com/users/AberSheeran/following{/other_user}","gists_url":"https://api.github.com/users/AberSheeran/gists{/gist_id}","starred_url":"https://api.github.com/users/AberSheeran/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AberSheeran/subscriptions","organizations_url":"https://api.github.com/users/AberSheeran/orgs","repos_url":"https://api.github.com/users/AberSheeran/repos","events_url":"https://api.github.com/users/AberSheeran/events{/privacy}","received_events_url":"https://api.github.com/users/AberSheeran/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-16T15:22:37Z","updated_at":"2018-04-17T04:44:25Z","closed_at":"2018-04-17T04:44:25Z","author_association":"NONE","body":"When I use code from Sanic'document like this\r\n```python\r\nfrom sanic.response import json\r\n\r\n@app.route(\"/files\")\r\ndef post_json(request):\r\n    test_file = request.files.get('test')\r\n\r\n    return json({ \"received\": True, \"file_names\": request.files.keys() })\r\n```\r\nHTML code like this\r\n```html\r\n<form action=\"/files\">\r\n<input type=\"file\" name=\"test\" />\r\n<button type=\"submit\">submit</button>\r\n</form>\r\n```\r\nThe response's file_names is `[]`\r\n\r\nCan you tell me what should I do? QAQ","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1192","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1192/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1192/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1192/events","html_url":"https://github.com/channelcat/sanic/issues/1192","id":314336786,"number":1192,"title":"Installing Sanic on Windows for PyCharm?","user":{"login":"SuperSajuuk","id":8324490,"avatar_url":"https://avatars2.githubusercontent.com/u/8324490?v=4","gravatar_id":"","url":"https://api.github.com/users/SuperSajuuk","html_url":"https://github.com/SuperSajuuk","followers_url":"https://api.github.com/users/SuperSajuuk/followers","following_url":"https://api.github.com/users/SuperSajuuk/following{/other_user}","gists_url":"https://api.github.com/users/SuperSajuuk/gists{/gist_id}","starred_url":"https://api.github.com/users/SuperSajuuk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/SuperSajuuk/subscriptions","organizations_url":"https://api.github.com/users/SuperSajuuk/orgs","repos_url":"https://api.github.com/users/SuperSajuuk/repos","events_url":"https://api.github.com/users/SuperSajuuk/events{/privacy}","received_events_url":"https://api.github.com/users/SuperSajuuk/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-14T15:18:58Z","updated_at":"2018-04-14T20:34:52Z","closed_at":"2018-04-14T20:34:52Z","author_association":"NONE","body":"Hi there. I'm trying to install Sanic on my Python 3.6.1 installation for usage in PyCharm. But it seems that the module won't install via PyCharm natively because of uvloop/ujson not being supported on Windows.\r\n\r\nI checked the issue tracker and saw this has been fixed, but I still keep running into the issue no matter what and it's preventing me using Sanic to develop a dashboard for my Discord Moderator Bot (it uses Flask, but that's inherently slow/not async).\r\n\r\nHopefully you can give some tips on how to install Sanic for PyCharm :D","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1187","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1187/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1187/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1187/events","html_url":"https://github.com/channelcat/sanic/issues/1187","id":311689537,"number":1187,"title":"Access request context globally","user":{"login":"cyrbil","id":1126098,"avatar_url":"https://avatars1.githubusercontent.com/u/1126098?v=4","gravatar_id":"","url":"https://api.github.com/users/cyrbil","html_url":"https://github.com/cyrbil","followers_url":"https://api.github.com/users/cyrbil/followers","following_url":"https://api.github.com/users/cyrbil/following{/other_user}","gists_url":"https://api.github.com/users/cyrbil/gists{/gist_id}","starred_url":"https://api.github.com/users/cyrbil/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/cyrbil/subscriptions","organizations_url":"https://api.github.com/users/cyrbil/orgs","repos_url":"https://api.github.com/users/cyrbil/repos","events_url":"https://api.github.com/users/cyrbil/events{/privacy}","received_events_url":"https://api.github.com/users/cyrbil/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-04-05T16:51:25Z","updated_at":"2018-04-06T06:29:27Z","closed_at":"2018-04-06T06:29:27Z","author_association":"NONE","body":"Flask allows to access `request` context instance from anywhere in the code, simply by importing `flask.request`. An exception is thrown when there is no context (app is starting or request is already finished).\r\n\r\nThis is no similar context proxy in sanic and it became tricky to get it when outside an handler.  \r\nOne use case that we got is, being able to get the current request and add more context to the logs (url, method, ... ect) when they are created from within a request context.\r\n\r\n\r\nOne dirty workaround:\r\n\r\n```\r\n    def get_request(limit=20):\r\n        \"\"\" sanic does not provide a globally accessible request context\r\n             so we inspect previous frames to get one\r\n        \"\"\"\r\n        frame = sys._getframe()\r\n        request = None\r\n        while frame and limit > 0:\r\n            f_locals = frame.f_locals\r\n            if 'request' in f_locals:\r\n                f_request = f_locals['request']\r\n                if isinstance(f_request, Request):\r\n                    request = f_request\r\n                    break\r\n            frame = frame.f_back\r\n            limit -= 1\r\n        return request\r\n```\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1186","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1186/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1186/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1186/events","html_url":"https://github.com/channelcat/sanic/issues/1186","id":311487888,"number":1186,"title":"Imported 0 records. Simplifying into dataframe...","user":{"login":"sunbarve","id":17616433,"avatar_url":"https://avatars2.githubusercontent.com/u/17616433?v=4","gravatar_id":"","url":"https://api.github.com/users/sunbarve","html_url":"https://github.com/sunbarve","followers_url":"https://api.github.com/users/sunbarve/followers","following_url":"https://api.github.com/users/sunbarve/following{/other_user}","gists_url":"https://api.github.com/users/sunbarve/gists{/gist_id}","starred_url":"https://api.github.com/users/sunbarve/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sunbarve/subscriptions","organizations_url":"https://api.github.com/users/sunbarve/orgs","repos_url":"https://api.github.com/users/sunbarve/repos","events_url":"https://api.github.com/users/sunbarve/events{/privacy}","received_events_url":"https://api.github.com/users/sunbarve/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-04-05T06:33:18Z","updated_at":"2018-04-05T09:20:14Z","closed_at":"2018-04-05T09:20:14Z","author_association":"NONE","body":"I am using **mongolite** package for connecting with **mongoDB**. \r\nI am trying to fetch data **by UserID** \r\n**df <- mongo$find('{\"UserID\":{\"$oid\":\"5a0d640c47c3921557099f76\"}}')**\r\nbut not getting record, querry is returning this -\r\n**Imported 0 records. Simplifying into dataframe...**","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1184","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1184/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1184/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1184/events","html_url":"https://github.com/channelcat/sanic/issues/1184","id":310971213,"number":1184,"title":"Question: Sanic blocking on time.sleep in async function","user":{"login":"rubenvdham","id":31563926,"avatar_url":"https://avatars1.githubusercontent.com/u/31563926?v=4","gravatar_id":"","url":"https://api.github.com/users/rubenvdham","html_url":"https://github.com/rubenvdham","followers_url":"https://api.github.com/users/rubenvdham/followers","following_url":"https://api.github.com/users/rubenvdham/following{/other_user}","gists_url":"https://api.github.com/users/rubenvdham/gists{/gist_id}","starred_url":"https://api.github.com/users/rubenvdham/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rubenvdham/subscriptions","organizations_url":"https://api.github.com/users/rubenvdham/orgs","repos_url":"https://api.github.com/users/rubenvdham/repos","events_url":"https://api.github.com/users/rubenvdham/events{/privacy}","received_events_url":"https://api.github.com/users/rubenvdham/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-03T19:42:42Z","updated_at":"2018-04-04T17:18:59Z","closed_at":"2018-04-04T17:18:59Z","author_association":"NONE","body":"I'm currently writing an authentication API (using sanic-auth). This is my Login route+function:\r\n\r\n`@app.route('/login', methods=['GET', 'POST'])\r\nasync def login(request):\r\n    if request.method == \"GET\":\r\n        return response.html(env.get_template(\"login.html\").render())\r\n    if request.method == 'POST':\r\n        validation = await validate_login_data(request)\r\n        if validation[0] and validation[1].check_password(request.form.get(\"password\")):\r\n            auth.login_user(request,validation[1])\r\n            return response.redirect(\"/\")\r\n        else:\r\n            raise loginException(\"Password incorrect\")\r\n    return response.text(\"Notloggedin\")`\r\n\r\nThe function `async def validate_login_data(request)` (which is awaited) contains one `time.sleep(5) ` for testing purposes. The time.sleep simulates a super long database query/blocking event. When I try to login with 2 different browserwindows to simulate multiple users logging in at the same time, the first login attempt blocks Sanic in handling requests. \r\nI expected this would not happen because the `validate_login_data(request)` function is being awaited and in the 5 seconds of waiting/querying (technically) other requests could be served. What am I doing wrong? I guess I'm not getting the async/await idea behind Python or maybe the time.sleep stops the whole event loop thingy, although the function is still async.\r\nI would really like to find out what is actually going on:)\r\nThanks in advance!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1182","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1182/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1182/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1182/events","html_url":"https://github.com/channelcat/sanic/issues/1182","id":310189448,"number":1182,"title":"Exception handling on app level","user":{"login":"smlbiobot","id":25040297,"avatar_url":"https://avatars0.githubusercontent.com/u/25040297?v=4","gravatar_id":"","url":"https://api.github.com/users/smlbiobot","html_url":"https://github.com/smlbiobot","followers_url":"https://api.github.com/users/smlbiobot/followers","following_url":"https://api.github.com/users/smlbiobot/following{/other_user}","gists_url":"https://api.github.com/users/smlbiobot/gists{/gist_id}","starred_url":"https://api.github.com/users/smlbiobot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/smlbiobot/subscriptions","organizations_url":"https://api.github.com/users/smlbiobot/orgs","repos_url":"https://api.github.com/users/smlbiobot/repos","events_url":"https://api.github.com/users/smlbiobot/events{/privacy}","received_events_url":"https://api.github.com/users/smlbiobot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-03-30T23:12:53Z","updated_at":"2018-04-01T13:47:41Z","closed_at":"2018-03-31T23:35:40Z","author_association":"NONE","body":"Per docs here: https://sanic.readthedocs.io/en/latest/sanic/exceptions.html\r\n\r\nI have handled `NotFound` and `ServerError` â€”Â but I have noticed that it doesnâ€™t cover all exceptions. Do I have to do this for every one of my blueprints as well? I ask because I am seeing 500s reported even with this added. Whatâ€˜s the best way to go about this?\r\n\r\nThanks!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1174","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/events","html_url":"https://github.com/channelcat/sanic/issues/1174","id":308112703,"number":1174,"title":"Variable names overriding other routes'?","user":{"login":"WilliamMayor","id":403126,"avatar_url":"https://avatars1.githubusercontent.com/u/403126?v=4","gravatar_id":"","url":"https://api.github.com/users/WilliamMayor","html_url":"https://github.com/WilliamMayor","followers_url":"https://api.github.com/users/WilliamMayor/followers","following_url":"https://api.github.com/users/WilliamMayor/following{/other_user}","gists_url":"https://api.github.com/users/WilliamMayor/gists{/gist_id}","starred_url":"https://api.github.com/users/WilliamMayor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/WilliamMayor/subscriptions","organizations_url":"https://api.github.com/users/WilliamMayor/orgs","repos_url":"https://api.github.com/users/WilliamMayor/repos","events_url":"https://api.github.com/users/WilliamMayor/events{/privacy}","received_events_url":"https://api.github.com/users/WilliamMayor/received_events","type":"User","site_admin":false},"labels":[{"id":382692937,"url":"https://api.github.com/repos/channelcat/sanic/labels/question","name":"question","color":"cc317c","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-03-23T17:13:34Z","updated_at":"2018-03-26T08:28:13Z","closed_at":"2018-03-25T07:20:19Z","author_association":"NONE","body":"I think there's a strong possibility that this is a mistake on my part, but I can't find anything about it.\r\n\r\nIf I have two routes with the same path, but different methods, also with differently named path variables, then one variable name overrides the other. Causing the second method to fail because it doesn't get given the variables it was expecting. Here's an example:\r\n\r\n```\r\n@app.route('/foo/<public_id>/', methods=['GET'])\r\ndef get_foo(public_id):\r\n    ...\r\n\r\n@app.route('/foo/<id>/, methods=['DELETE'])\r\ndef delete_foo(id):\r\n    ...\r\n```\r\n\r\n`delete_foo` fails because it is given an \"unexpected keyword argument 'public_id'\".\r\n\r\nIn my case I have a shareable URL that my users can share with friends. The delete method should remain private, and is given a different ID.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1172","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/events","html_url":"https://github.com/channelcat/sanic/issues/1172","id":307959827,"number":1172,"title":"Sanic and subprocesses for CPU intensive work","user":{"login":"kinware","id":2056837,"avatar_url":"https://avatars3.githubusercontent.com/u/2056837?v=4","gravatar_id":"","url":"https://api.github.com/users/kinware","html_url":"https://github.com/kinware","followers_url":"https://api.github.com/users/kinware/followers","following_url":"https://api.github.com/users/kinware/following{/other_user}","gists_url":"https://api.github.com/users/kinware/gists{/gist_id}","starred_url":"https://api.github.com/users/kinware/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kinware/subscriptions","organizations_url":"https://api.github.com/users/kinware/orgs","repos_url":"https://api.github.com/users/kinware/repos","events_url":"https://api.github.com/users/kinware/events{/privacy}","received_events_url":"https://api.github.com/users/kinware/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-03-23T09:42:01Z","updated_at":"2018-03-25T07:54:37Z","closed_at":"2018-03-25T07:54:36Z","author_association":"CONTRIBUTOR","body":"I'm trying to get Sanic (and uvloop) to use a worker pool of sub-processes for CPU intensive requests. So far I've come up with the below code. The example \"work\" is first run once (to ensure the process pool works as intended). Then sanic is started and the user can trigger the \"work\" through HTTP. See below.\r\n\r\n```\r\nimport asyncio\r\nimport concurrent\r\nimport os\r\nimport time\r\nimport uvloop\r\n\r\nfrom sanic import Sanic, response, config\r\n\r\n\r\n# Define a CPU bound worker function\r\ndef deep_thought(data):\r\n    print(\"Working to answer: \" + data)\r\n    time.sleep(5)  # Actually not CPU bound in this example, but outcome should be identical\r\n    return 42\r\n\r\n# Enable extra asyncio debugging\r\nos.environ['PYTHONASYNCIODEBUG'] = \"1\"\r\n\r\n# Make sure uvloop is used as event loop by default\r\nasyncio.set_event_loop_policy(uvloop.EventLoopPolicy())\r\n\r\n# Instantiate an event loop object for main thread\r\nloop = asyncio.get_event_loop()\r\n\r\n# Create ProcessPoolExecutor\r\nexecutor = concurrent.futures.ProcessPoolExecutor(max_workers=5)\r\n\r\n# Define a coroutine that will call the CPU bound function in a sub process\r\nasync def ask_question():\r\n    res = await loop.run_in_executor(\r\n        executor,\r\n        deep_thought,\r\n        \"What's the answer to life, the universe and everything? (no sanic)\",\r\n    )\r\n    print('Answer (no sanic): ' + str(res))\r\n\r\n# Create a task and run it in the the event loop\r\nprint('Asking question without sanic started')\r\ntask = loop.create_task(ask_question())\r\nloop.run_until_complete(task)\r\n\r\n# Create the Sanic app which should(?!?) use the same event loop as create above\r\nconfig.Config.LOGO = None\r\napp = Sanic()\r\n\r\n\r\n# Endpoint to test server responsiveness\r\n@app.route(\"/\")\r\nasync def root(request):\r\n    return response.json({\"root\": True})\r\n\r\n\r\n# CPU bound endpoint\r\n@app.route(\"/ask\")\r\nasync def ask(request):\r\n    res = await loop.run_in_executor(\r\n        executor,\r\n        deep_thought,\r\n        \"What's the answer to life, the universe and everything? (sanic)\"\r\n    )\r\n    return response.json({\"result\": res})\r\n\r\n\r\n# Run the Sanic app (which will start the event loop again)\r\napp.run(host=\"0.0.0.0\", port=12000, debug=True)\r\n```\r\n\r\nI run the above using sanic from master branch, uvloop 0.8.1 together with python 3.6.3. The first run of the worker function in a subprocess (before starting sanic) works fine. However, when initiating the work through sanic (http://localhost:12000/ask) it bombs with an exception:\r\n\r\n```\r\n$ python3.6 ./test_sanic_subprocess.py\r\nAsking question without sanic started\r\nWorking to answer: What's the answer to life, the universe and everything? (no sanic)\r\nAnswer (no sanic): 42\r\n[2018-03-23 10:24:16 +0100] [19475] [INFO] Goin' Fast @ http://0.0.0.0:12000\r\n[2018-03-23 10:24:16 +0100] [19475] [INFO] Starting worker [19475]\r\n[2018-03-23 10:24:19 +0100] - (sanic.access)[INFO][127.0.0.1:51520]: GET http://localhost:12000/  200 13\r\n[2018-03-23 10:24:23 +0100] [19475] [ERROR] Traceback (most recent call last):\r\n  File \"/home/kinware/src/sanic/sanic/app.py\", line 597, in handle_request\r\n    response = await response\r\n  File \"/home/kinware/python/lib/python3.6/asyncio/coroutines.py\", line 128, in throw\r\n    return self.gen.throw(type, value, traceback)\r\n  File \"./test_subprocess_nosanic.py\", line 59, in ask\r\n    \"What's the answer to life, the universe and everything? (sanic)\"\r\nRuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /home/kinware/src/sanic/sanic/app.py:597> cr
8000
eated at /home/kinware/src/sanic/sanic/server.py:304> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel()] created at ./test_subprocess_nosanic.py:59> attached to a different loop\r\n\r\nWorking to answer: What's the answer to life, the universe and everything? (sanic)\r\n[2018-03-23 10:24:23 +0100] [19475] [ERROR] Exception occurred while handling uri: \"http://localhost:12000/ask\"\r\nTraceback (most recent call last):\r\n  File \"/home/kinware/src/sanic/sanic/app.py\", line 597, in handle_request\r\n    response = await response\r\n  File \"/home/kinware/python/lib/python3.6/asyncio/coroutines.py\", line 128, in throw\r\n    return self.gen.throw(type, value, traceback)\r\n  File \"./test_subprocess_nosanic.py\", line 59, in ask\r\n    \"What's the answer to life, the universe and everything? (sanic)\"\r\nRuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /home/kinware/src/sanic/sanic/app.py:597> created at /home/kinware/src/sanic/sanic/server.py:304> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel()] created at ./test_subprocess_nosanic.py:59> attached to a different loop\r\n\r\n[2018-03-23 10:24:23 +0100] - (sanic.access)[INFO][127.0.0.1:51520]: GET http://localhost:12000/ask  500 2977\r\n```\r\n\r\nIt appears from the exceptions that there are multiple event loops in play here, but I'm not quite sure why/where these are created. Maybe I'm misunderstanding the python event loop concept? Also not sure what happens when the current process fork()s and the child worker processes inherits the event loop from the master process.\r\n\r\nAny ideas what I'm doing wrong here?\r\n\r\nIf I can get it working I'd be happy to submit a PR for sanic/examples/ showing how to handle CPU intensive work in a subprocess in conjunction with the normal async processing sanic does so well.\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1164","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1164/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1164/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1164/events","html_url":"https://github.com/channelcat/sanic/issues/1164","id":305845533,"number":1164,"title":"so, sanic still use the single core","user":{"login":"csrgxtu","id":5053620,"avatar_url":"https://avatars0.githubusercontent.com/u/5053620?v=4","gravatar_id":"","url":"https://api.github.com/users/csrgxtu","html_url":"https://github.com/csrgxtu","followers_url":"https://api.github.com/users/csrgxtu/followers","following_url":"https://api.github.com/users/csrgxtu/following{/other_user}","gists_url":"https://api.github.com/users/csrgxtu/gists{/gist_id}","starred_url":"https://api.github.com/users/csrgxtu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/csrgxtu/subscriptions","organizations_url":"https://api.github.com/users/csrgxtu/orgs","repos_url":"https://api.github.com/users/csrgxtu/repos","events_url":"https://api.github.com/users/csrgxtu/events{/privacy}","received_events_url":"https://api.github.com/users/csrgxtu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-03-16T08:50:29Z","updated_at":"2018-04-03T00:24:07Z","closed_at":"2018-04-03T00:24:07Z","author_association":"NONE","body":"as we know, Python 3.5's async is implemented through coroutine, but it still runs in single thread or process. so sanic is still in single thread or process, right?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1158","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/events","html_url":"https://github.com/channelcat/sanic/issues/1158","id":304685913,"number":1158,"title":"[Suggestion]: auto reload","user":{"login":"AberSheeran","id":25364828,"avatar_url":"https://avatars3.githubusercontent.com/u/25364828?v=4","gravatar_id":"","url":"https://api.github.com/users/AberSheeran","html_url":"https://github.com/AberSheeran","followers_url":"https://api.github.com/users/AberSheeran/followers","following_url":"https://api.github.com/users/AberSheeran/following{/other_user}","gists_url":"https://api.github.com/users/AberSheeran/gists{/gist_id}","starred_url":"https://api.github.com/users/AberSheeran/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AberSheeran/subscriptions","organizations_url":"https://api.github.com/users/AberSheeran/orgs","repos_url":"https://api.github.com/users/AberSheeran/repos","events_url":"https://api.github.com/users/AberSheeran/events{/privacy}","received_events_url":"https://api.github.com/users/AberSheeran/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2018-03-13T09:27:48Z","updated_at":"2018-03-29T19:35:49Z","closed_at":"2018-03-14T05:51:00Z","author_association":"NONE","body":"When the code be changed with DEBUG=Trueï¼ŒServer will reload like flask.\r\n\r\nWhy not do thatï¼Ÿ ","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1152","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1152/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1152/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1152/events","html_url":"https://github.com/channelcat/sanic/issues/1152","id":303271800,"number":1152,"title":"Question - asynchronous work with progress indicator not behaving properly with more than 1 worker.","user":{"login":"UNIcodeX","id":8235002,"avatar_url":"https://avatars2.githubusercontent.com/u/8235002?v=4","gravatar_id":"","url":"https://api.github.com/users/UNIcodeX","html_url":"https://github.com/UNIcodeX","followers_url":"https://api.github.com/users/UNIcodeX/followers","following_url":"https://api.github.com/users/UNIcodeX/following{/other_user}","gists_url":"https://api.github.com/users/UNIcodeX/gists{/gist_id}","starred_url":"https://api.github.com/users/UNIcodeX/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/UNIcodeX/subscriptions","organizations_url":"https://api.github.com/users/UNIcodeX/orgs","repos_url":"https://api.github.com/users/UNIcodeX/repos","events_url":"https://api.github.com/users/UNIcodeX/events{/privacy}","received_events_url":"https://api.github.com/users/UNIcodeX/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-03-07T21:47:12Z","updated_at":"2018-04-08T20:40:01Z","closed_at":"2018-04-08T20:40:01Z","author_association":"NONE","body":"I've put together a small web app to trigger some work, and be able to poll the results of that work. This is an attempt to explore the possibility of using asyncio, rather than celery, to perform some work and be able to interact with its progress.\r\n\r\nIf the workers are set to more than 1, then the status does not display, and I think this has to do with the session, but wanted to ask the Sanic devs directly for input on how to make this work as intended with multiple workers.\r\n\r\nThe gist for it is in the link below:\r\nhttps://gist.github.com/UNIcodeX/f1ee8579719fbef6edaad71c96cd0fe2\r\n\r\nThank you in advance for your time.\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1150","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/events","html_url":"https://github.com/channelcat/sanic/issues/1150","id":301997681,"number":1150,"title":"UnicodeEncodeError on server startup","user":{"login":"antonagestam","id":218551,"avatar_url":"https://avatars0.githubusercontent.com/u/218551?v=4","gravatar_id":"","url":"https://api.github.com/users/antonagestam","html_url":"https://github.com/antonagestam","followers_url":"https://api.github.com/users/antonagestam/followers","following_url":"https://api.github.com/users/antonagestam/following{/other_user}","gists_url":"https://api.github.com/users/antonagestam/gists{/gist_id}","starred_url":"https://api.github.com/users/antonagestam/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/antonagestam/subscriptions","organizations_url":"https://api.github.com/users/antonagestam/orgs","repos_url":"https://api.github.com/users/antonagestam/repos","events_url":"https://api.github.com/users/antonagestam/events{/privacy}","received_events_url":"https://api.github.com/users/antonagestam/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-03-03T13:20:18Z","updated_at":"2018-03-03T13:24:57Z","closed_at":"2018-03-03T13:24:40Z","author_association":"NONE","body":"Stumbled on a strange and kinda funny problem, it seems like sanic fails to print sanic on startup. It seems like the server is otherwise functioning healthy. This might very well be a problem with my environment and not with sanic per se.\r\n\r\n```\r\n$Â python -m server.server\r\n--- Logging error ---\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py\", line 994, in emit\r\n    stream.write(msg)\r\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 62-66: ordinal not in range(128)\r\nCall stack:\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/Users/antonagestam/python_projects/achtung/server/server.py\", line 73, in <module>\r\n    app.run(host=\"0.0.0.0\", port=port, debug=True)\r\n  File \"/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py\", line 641, in run\r\n    access_log=access_log)\r\n  File \"/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py\", line 803, in _helper\r\n    logger.debug(self.config.LOGO)\r\nMessage: '\\n                 \\u2584\\u2584\\u2584\\u2584\\u2584\\n        \\u2580\\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2584\\u2584       _______________\\n      \\u2584\\u2584\\u2584\\u2584\\u2584  \\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584  /                 \\\\\\n     \\u2580\\u2580\\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u258c \\u2580\\u2590\\u2584 \\u2580\\u2590\\u2588 |   Gotta go fast!  |\\n   \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2584 \\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2588\\u2588 | _________________/\\n   \\u2580\\u2584\\u2584\\u2584\\u2584\\u2584  \\u2580\\u2580\\u2588\\u2584\\u2580\\u2588\\u2550\\u2550\\u2550\\u2550\\u2588\\u2580 |/\\n        \\u2580\\u2580\\u2580\\u2584  \\u2580\\u2580\\u2588\\u2588\\u2588 \\u2580       \\u2584\\u2584\\n     \\u2584\\u2588\\u2588\\u2588\\u2580\\u2580\\u2588\\u2588\\u2584\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584 \\u2584\\u2580\\u2580\\u2580\\u2580\\u2580\\u2580\\u2588\\u258c\\n   \\u2588\\u2588\\u2580\\u2584\\u2584\\u2584\\u2588\\u2588\\u2580\\u2584\\u2588\\u2588\\u2588\\u2580 \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588      \\u2584\\u2588\\u2588\\n\\u2584\\u2580\\u2580\\u2580\\u2584\\u2588\\u2588\\u2584\\u2580\\u2580\\u258c\\u2588\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2592\\u2592\\u2588\\u2588\\u2588     \\u258c\\u2584\\u2584\\u2580\\n\\u258c    \\u2590\\u2580\\u2588\\u2588\\u2588\\u2588\\u2590\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2592\\u2590\\u2588\\u2588\\u258c\\n\\u2580\\u2584\\u2584\\u2584\\u2584\\u2580   \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2584\\u2588\\u2588\\u2580\\n          \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2580\\n        \\u2584\\u2584\\u2588\\u2588\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2580\\u2588\\n      \\u2584\\u2588\\u2588\\u2580     \\u2580\\u2580\\u2580  \\u2588\\n     \\u2584\\u2588             \\u2590\\u258c\\n \\u2584\\u2584\\u2584\\u2584\\u2588\\u258c              \\u2580\\u2588\\u2584\\u2584\\u2584\\u2584\\u2580\\u2580\\u2584\\n\\u258c     \\u2590                \\u2580\\u2580\\u2584\\u2584\\u2584\\u2580\\n \\u2580\\u2580\\u2584\\u2584\\u2580\\n'\r\nArguments: ()\r\n[2018-03-03 14:10:43 +0100] [36439] [INFO] Goin' Fast @ http://0.0.0.0:8000\r\n[2018-03-03 14:10:43 +0100] [36439] [INFO] Starting worker [36439]\r\n```\r\n\r\n\r\n```\r\n$Â pip freeze\r\naiofiles==0.3.2\r\naioredis==1.0.0\r\nasync-timeout==2.0.0\r\nhiredis==0.2.0\r\nhttptools==0.0.10\r\nsanic==0.7.0\r\nujson==1.35\r\nuvloop==0.9.1\r\nwebsockets==4.0.1\r\n$ python --version\r\nPython 3.6.1\r\n$ uname -a\r\nDarwin dev-antonagestam 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64\r\n```\r\n\r\n(macos 10.13.3)","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1148","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/events","html_url":"https://github.com/channelcat/sanic/issues/1148","id":301343132,"number":1148,"title":"How to catch method_not_supported exception?","user":{"login":"singpenguin","id":1811606,"avatar_url":"https://avatars0.githubusercontent.com/u/1811606?v=4","gravatar_id":"","url":"https://api.github.com/users/singpenguin","html_url":"https://github.com/singpenguin","followers_url":"https://api.github.com/users/singpenguin/followers","following_url":"https://api.github.com/users/singpenguin/following{/other_user}","gists_url":"https://api.github.com/users/singpenguin/gists{/gist_id}","starred_url":"https://api.github.com/users/singpenguin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/singpenguin/subscriptions","organizations_url":"https://api.github.com/users/singpenguin/orgs","repos_url":"https://api.github.com/users/singpenguin/repos","events_url":"https://api.github.com/users/singpenguin/events{/privacy}","received_events_url":"https://api.github.com/users/singpenguin/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-03-01T10:00:18Z","updated_at":"2018-03-02T02:10:53Z","closed_at":"2018-03-02T02:10:53Z","author_association":"NONE","body":"I want to catch the exception \"method_not_supported\", and customer result , how to do?\r\nThank you!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1147","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1147/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1147/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1147/events","html_url":"https://github.com/channelcat/sanic/issues/1147","id":300978386,"number":1147,"title":"websocket handlers returning 404 (or other status codes)","user":{"login":"abingham","id":79224,"avatar_url":"https://avatars2.githubusercontent.com/u/79224?v=4","gravatar_id":"","url":"https://api.github.com/users/abingham","html_url":"https://github.com/abingham","followers_url":"https://api.github.com/users/abingham/followers","following_url":"https://api.github.com/users/abingham/following{/other_user}","gists_url":"https://api.github.com/users/abingham/gists{/gist_id}","starred_url":"https://api.github.com/users/abingham/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/abingham/subscriptions","organizations_url":"https://api.github.com/users/abingham/orgs","repos_url":"https://api.github.com/users/abingham/repos","events_url":"https://api.github.com/users/abingham/events{/privacy}","received_events_url":"https://api.github.com/users/abingham/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-02-28T10:54:05Z","updated_at":"2018-05-12T08:41:08Z","closed_at":"2018-05-12T08:41:08Z","author_association":"NONE","body":"I've got a websocket handler which, under certain circumstances, I'd like to return 404 to the user rather than set up the websocket. To do this I'm simply raising `sanic.exceptions.NotFound` from the handler. However when I actually exercise this code what I see is this:\r\n```\r\nTraceback (most recent call last):\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/websockets/handshake.py\", line 85, in check_request\r\n    assert get_header('Upgrade').lower() == 'websocket'\r\nAssertionError\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/websocket.py\", line 63, in websocket_handshake\r\n    key = handshake.check_request(get_header)\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/websockets/handshake.py\", line 93, in check_request\r\n    raise InvalidHandshake(\"Invalid request\") from exc\r\nwebsockets.exceptions.InvalidHandshake: Invalid request\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py\", line 556, in handle_request\r\n    response = await response\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py\", line 259, in websocket_handler\r\n    ws = await protocol.websocket_handshake(request, subprotocols)\r\n  File \"/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/websocket.py\", line 66, in websocket_handshake\r\n    raise InvalidUsage('Invalid websocket request')\r\nsanic.exceptions.InvalidUsage: Invalid websocket request\r\n```\r\n\r\nThat is, I get a 400 response from the `InvalidUsage` exception.\r\n\r\nAm I just wrong in expecting to be able to return a 404? I'd be happy to be told that there's a (justifiable) reason not to be allowed to do this.\r\n\r\nIf it should be supported, am I doing something wrong here, or is this a bug in sanic/websockets/something?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1144","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1144/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1144/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1144/events","html_url":"https://github.com/channelcat/sanic/issues/1144","id":300479364,"number":1144,"title":"Unique ID for workers?","user":{"login":"smlbiobot","id":25040297,"avatar_url":"https://avatars0.githubusercontent.com/u/25040297?v=4","gravatar_id":"","url":"https://api.github.com/users/smlbiobot","html_url":"https://github.com/smlbiobot","followers_url":"https://api.github.com/users/smlbiobot/followers","following_url":"https://api.github.com/users/smlbiobot/following{/other_user}","gists_url":"https://api.github.com/users/smlbiobot/gists{/gist_id}","starred_url":"https://api.github.com/users/smlbiobot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/smlbiobot/subscriptions","organizations_url":"https://api.github.com/users/smlbiobot/orgs","repos_url":"https://api.github.com/users/smlbiobot/repos","events_url":"https://api.github.com/users/smlbiobot/events{/privacy}","received_events_url":"https://api.github.com/users/smlbiobot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2018-02-27T03:16:59Z","updated_at":"2018-04-28T16:26:27Z","closed_at":"2018-04-28T16:26:27Z","author_association":"NONE","body":"I am using APScheduler to process some background tasks. \r\n\r\nhttp://apscheduler.readthedocs.io/en/latest/userguide.html\r\n\r\nWhen I use this on the production server with multiple workers, e.g. 4 â€”Â I noticed that itâ€™s possible that the APScheduler gets instantiated four times and thus if I then run background tasks that are scheduled, it also gets run four times, significantly impacting system resources.\r\n\r\nWhat I would like to know is if it is possible to somehow identify the worker instance while inside the app. A user using a different framework uses this interesting solution but I donâ€™t know how I might implement something similar in Sanic:\r\n\r\nhttps://github.com/agronholm/apscheduler/issues/160#issuecomment-254535386\r\n\r\nAny help would be greatly appreciated!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1140","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/events","html_url":"https://github.com/channelcat/sanic/issues/1140","id":299429100,"number":1140,"title":"Workers settings â€” related to cores or not?","user":{"login":"smlbiobot","id":25040297,"avatar_url":"https://avatars0.githubusercontent.com/u/25040297?v=4","gravatar_id":"","url":"https://api.github.com/users/smlbiobot","html_url":"https://github.com/smlbiobot","followers_url":"https://api.github.com/users/smlbiobot/followers","following_url":"https://api.github.com/users/smlbiobot/following{/other_user}","gists_url":"https://api.github.com/users/smlbiobot/gists{/gist_id}","starred_url":"https://api.github.com/users/smlbiobot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/smlbiobot/subscriptions","organizations_url":"https://api.github.com/users/smlbiobot/orgs","repos_url":"https://api.github.com/users/smlbiobot/repos","events_url":"https://api.github.com/users/smlbiobot/events{/privacy}","received_events_url":"https://api.github.com/users/smlbiobot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-02-22T16:54:18Z","updated_at":"2018-02-25T17:15:28Z","closed_at":"2018-02-25T17:15:28Z","author_association":"NONE","body":"On my server, I used to set my workers to 4 because I have 4 cores. However, I just set my DB to use 2, should I in fact set my workers to 2 or can it actually still be 4 if my processors are fast enough? Are the two related or is it just for threading?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1136","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/events","html_url":"https://github.com/channelcat/sanic/issues/1136","id":298791858,"number":1136,"title":"restrictive call to handlers from sanic.handlers.ErrorHandler.response","user":{"login":"Julien00859","id":8208953,"avatar_url":"https://avatars2.githubusercontent.com/u/8208953?v=4","gravatar_id":"","url":"https://api.github.com/users/Julien00859","html_url":"https://github.com/Julien00859","followers_url":"https://api.github.com/users/Julien00859/followers","following_url":"https://api.github.com/users/Julien00859/following{/other_user}","gists_url":"https://api.github.com/users/Julien00859/gists{/gist_id}","starred_url":"https://api.github.com/users/Julien00859/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Julien00859/subscriptions","organizations_url":"https://api.github.com/users/Julien00859/orgs","repos_url":"https://api.github.com/users/Julien00859/repos","events_url":"https://api.github.com/users/Julien00859/events{/privacy}","received_events_url":"https://api.github.com/users/Julien00859/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-02-20T23:47:14Z","updated_at":"2018-02-21T15:55:56Z","closed_at":"2018-02-21T15:55:56Z","author_association":"CONTRIBUTOR","body":"`sanic.handlers.ErrorHandler.response` use keywords arguments on handler call and so force the signature of the handler\r\n\r\nConsider this very basic application:\r\n\r\n```python\r\nfrom sanic import Sanic\r\nfrom sanic.exceptions import SanicException\r\nfrom sanic.response import text\r\n\r\napp = Sanic()\r\n\r\n@app.exception(SanicException)\r\ndef http_error_handler(request, exception):\r\n\treturn text(\":(\")\r\n\r\napp.run()\r\n```\r\n\r\nit works as intended:\r\n\r\n\t$ python server.py \r\n\t[2018-02-21 00:35:04 +0100] [23560] [INFO] Goin' Fast @ http://127.0.0.1:8000\r\n\t[2018-02-21 00:35:04 +0100] [23560] [INFO] Starting worker [23560]\r\n\t[2018-02-21 00:35:16 +0100] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/  200 2\r\n\t[2018-02-21 00:36:01 +0100] [23560] [INFO] Stopping worker [23560]\r\n\t[2018-02-21 00:36:01 +0100] [23560] [INFO] Server Stopped\r\n\r\nBut you cannot change the argument names:\r\n\r\n```python\r\n@app.exception(SanicException)\r\ndef http_error_handler(req, exc):\r\n\treturn text(\":(\")\r\n```\r\n\r\nbecause `ErrorHandler.response` use keyword arguments:\r\n\r\n\t$ python server.py \r\n\t[2018-02-21 00:36:02 +0100] [23608] [INFO] Goin' Fast @ http://127.0.0.1:8000\r\n\t[2018-02-21 00:36:02 +0100] [23608] [INFO] Starting worker [23608]\r\n\t[2018-02-21 00:36:05 +0100] [23608] [ERROR] Traceback (most recent call last):\r\n\t  File \"[..]/sanic/app.py\", line 546, in handle_request\r\n\t    handler, args, kwargs, uri = self.router.get(request)\r\n\t  File \"[..]/sanic/router.py\", line 344, in get\r\n\t    return self._get(request.path, request.method, '')\r\n\t  File \"[..]/sanic/router.py\", line 393, in _get\r\n\t    raise NotFound('Requested URL {} not found'.format(url))\r\n\tsanic.exceptions.NotFound: Requested URL / not found\r\n\r\n\tDuring handling of the above exception, another exception occurred:\r\n\r\n\tTraceback (most recent call last):\r\n\t  File \"[..]/sanic/handlers.py\", line 82, in response\r\n\t    response = handler(request=request, exception=exception)\r\n\tTypeError: http_error_handler() got an unexpected keyword argument 'request'\r\n\r\n\t[2018-02-21 00:36:05 +0100] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/  500 41\r\n\t[2018-02-21 00:36:10 +0100] [23608] [INFO] KeepAlive Timeout. Closing connection.\r\n\t[2018-02-21 00:38:27 +0100] [23608] [INFO] Stopping worker [23608]\r\n\t[2018-02-21 00:38:27 +0100] [23608] [INFO] Server Stopped\r\n\r\n\r\nA pull request is coming shortly to use regular arguments instead of keywords in the `ErrorHandler.response`.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1134","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/events","html_url":"https://github.com/channelcat/sanic/issues/1134","id":298456763,"number":1134,"title":"Release Schedule","user":{"login":"pyk","id":2213646,"avatar_url":"https://avatars3.githubusercontent.com/u/2213646?v=4","gravatar_id":"","url":"https://api.github.com/users/pyk","html_url":"https://github.com/pyk","followers_url":"https://api.github.com/users/pyk/followers","following_url":"https://api.github.com/users/pyk/following{/other_user}","gists_url":"https://api.github.com/users/pyk/gists{/gist_id}","starred_url":"https://api.github.com/users/pyk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pyk/subscriptions","organizations_url":"https://api.github.com/users/pyk/orgs","repos_url":"https://api.github.com/users/pyk/repos","events_url":"https://api.github.com/users/pyk/events{/privacy}","received_events_url":"https://api.github.com/users/pyk/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-02-20T02:50:46Z","updated_at":"2018-03-14T04:00:39Z","closed_at":"2018-03-14T04:00:39Z","author_association":"NONE","body":"Hey guys, I want to handle `MethodNotSupported` exceptions but found out that the branch `master` is not released yet. The lastest version is 0.7.0 https://github.com/channelcat/sanic/releases, When the master branch is released to the pypi?\r\n\r\nthanks","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1120","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/events","html_url":"https://github.com/channelcat/sanic/issues/1120","id":295831355,"number":1120,"title":"Passing the list into route decorator's host argument","user":{"login":"mexicarne","id":1031992,"avatar_url":"https://avatars3.githubusercontent.com/u/1031992?v=4","gravatar_id":"","url":"https://api.github.com/users/mexicarne","html_url":"https://github.com/mexicarne","followers_url":"https://api.github.com/users/mexicarne/followers","following_url":"https://api.github.com/users/mexicarne/following{/other_user}","gists_url":"https://api.github.com/users/mexicarne/gists{/gist_id}","starred_url":"https://api.github.com/users/mexicarne/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mexicarne/subscriptions","organizations_url":"https://api.github.com/users/mexicarne/orgs","repos_url":"https://api.github.com/users/mexicarne/repos","events_url":"https://api.github.com/users/mexicarne/events{/privacy}","received_events_url":"https://api.github.com/users/mexicarne/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-02-09T10:57:10Z","updated_at":"2018-02-16T19:12:28Z","closed_at":"2018-02-16T19:12:27Z","author_association":"NONE","body":"Hello,\r\n\r\naccording to the [docs](http://sanic.readthedocs.io/en/latest/sanic/routing.html#http-request-types) :\r\n> There is also an optional host argument (which can be a list or a string)\r\n\r\nBut if I try to pass a list into host argument, I got \r\n```python\r\nFile \"/path/lib/python3.6/site-packages/sanic/router.py\", line 216, in merge_route\r\n    uri, ','.join(list(duplicated))))\r\nsanic.router.RouteExists: Route already registered: test.com/post/ [POST]\r\n```\r\n\r\nHere is the test sample:\r\n```python\r\nfrom sanic import Sanic\r\nfrom sanic.response import text\r\n\r\napp = Sanic()\r\n\r\n@app.route('/post', methods=['POST'], host=['test.com', 'test2.com'])\r\nasync def post_handler(request):\r\n    return text('POST request for test.com - {}'.format(request.json))\r\n\r\n@app.route('/post', methods=
3b77
['POST'])\r\nasync def post_handler(request):\r\n    return text('POST request for default - {}'.format(request.json))\r\n\r\nif __name__ == '__main__':\r\n    app.run(host='127.0.0.1', port=8000)\r\n```\r\n\r\nI get the same exception if I'm passing the list with single value in it (`host=['test.com']`). Everything works as expected if host argument is a string though. Am I doing something wrong or it's a bug in documentation/sanic?\r\n\r\nSanic is installed from pip: sanic==0.7.0","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1119","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/events","html_url":"https://github.com/channelcat/sanic/issues/1119","id":294945731,"number":1119,"title":"Document websocket protocol arguments","user":{"login":"r0fls","id":1858004,"avatar_url":"https://avatars1.githubusercontent.com/u/1858004?v=4","gravatar_id":"","url":"https://api.github.com/users/r0fls","html_url":"https://github.com/r0fls","followers_url":"https://api.github.com/users/r0fls/followers","following_url":"https://api.github.com/users/r0fls/following{/other_user}","gists_url":"https://api.github.com/users/r0fls/gists{/gist_id}","starred_url":"https://api.github.com/users/r0fls/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/r0fls/subscriptions","organizations_url":"https://api.github.com/users/r0fls/orgs","repos_url":"https://api.github.com/users/r0fls/repos","events_url":"https://api.github.com/users/r0fls/events{/privacy}","received_events_url":"https://api.github.com/users/r0fls/received_events","type":"User","site_admin":false},"labels":[{"id":464611475,"url":"https://api.github.com/repos/channelcat/sanic/labels/beginner","name":"beginner","color":"c2e0c6","default":false},{"id":799208863,"url":"https://api.github.com/repos/channelcat/sanic/labels/documentation","name":"documentation","color":"f7e70c","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-02-06T23:05:44Z","updated_at":"2018-02-11T10:02:23Z","closed_at":"2018-02-11T10:02:23Z","author_association":"COLLABORATOR","body":"After https://github.com/channelcat/sanic/pull/1112 we are missing some documentation around the accepted arguments.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1118","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/events","html_url":"https://github.com/channelcat/sanic/issues/1118","id":294832295,"number":1118,"title":"Restic - a loose & flexible REST framework for Sanic. Inspired by Django REST Framework.","user":{"login":"and3rson","id":190107,"avatar_url":"https://avatars2.githubusercontent.com/u/190107?v=4","gravatar_id":"","url":"https://api.github.com/users/and3rson","html_url":"https://github.com/and3rson","followers_url":"https://api.github.com/users/and3rson/followers","following_url":"https://api.github.com/users/and3rson/following{/other_user}","gists_url":"https://api.github.com/users/and3rson/gists{/gist_id}","starred_url":"https://api.github.com/users/and3rson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/and3rson/subscriptions","organizations_url":"https://api.github.com/users/and3rson/orgs","repos_url":"https://api.github.com/users/and3rson/repos","events_url":"https://api.github.com/users/and3rson/events{/privacy}","received_events_url":"https://api.github.com/users/and3rson/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-06T16:49:47Z","updated_at":"2018-02-20T11:10:55Z","closed_at":"2018-02-20T11:10:55Z","author_association":"NONE","body":"Hi everyone,\r\n\r\nI can't even express how cool Sanic is. I've recently started using it and it looks like an amazing replacement for somehow outdated & conservative Django framework (which I've been using for over 5 years now).\r\n\r\nI'm currently building a well-documented and flexible REST framework for Sanic called Restic. It is somewhat inspired by Django REST Framework in terms of architecture, but actual implementation of things is going to be more verbose comparing to DRF. In fact, the only thing that is partially borrowed from DRF is the serializers/viewsets concept.\r\n\r\nIdeally by using Restic + Sanic I'm aiming to create an explicit & fast asyncio-based REST framework with the support of serializers & viewsets, streaming endpoints, OpenAPI schema generation, authentication & permissions etc. Main goal is to provide flexible & hackable REST implementation to your Sanic apps.\r\n\r\nLink to the repo: https://github.com/and3rson/restic\r\n\r\nThe project is currently on its alpha state.\r\n\r\nCollaborators are warmly welcome!\r\n\r\nI hope this is going to be interesting & useful to someone as much as it is to me.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1116","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/events","html_url":"https://github.com/channelcat/sanic/issues/1116","id":294298239,"number":1116,"title":"Please Add me - New Cairo, Egypt","user":{"login":"amirabehery","id":34469908,"avatar_url":"https://avatars3.githubusercontent.com/u/34469908?v=4","gravatar_id":"","url":"https://api.github.com/users/amirabehery","html_url":"https://github.com/amirabehery","followers_url":"https://api.github.com/users/amirabehery/followers","following_url":"https://api.github.com/users/amirabehery/following{/other_user}","gists_url":"https://api.github.com/users/amirabehery/gists{/gist_id}","starred_url":"https://api.github.com/users/amirabehery/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/amirabehery/subscriptions","organizations_url":"https://api.github.com/users/amirabehery/orgs","repos_url":"https://api.github.com/users/amirabehery/repos","events_url":"https://api.github.com/users/amirabehery/events{/privacy}","received_events_url":"https://api.github.com/users/amirabehery/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-02-05T07:38:05Z","updated_at":"2018-02-13T18:45:06Z","closed_at":"2018-02-13T18:45:06Z","author_association":"NONE","body":"## Hi Everyone! This issue is to track the addition of 'Cairo' to the map, which can be found at :\r\n- Longitude :  30.051382\r\n- Latitude : 31.460982","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1106","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/events","html_url":"https://github.com/channelcat/sanic/issues/1106","id":293162923,"number":1106,"title":"Add custom fields to the access logs","user":{"login":"gbnk0","id":6898551,"avatar_url":"https://avatars2.githubusercontent.com/u/6898551?v=4","gravatar_id":"","url":"https://api.github.com/users/gbnk0","html_url":"https://github.com/gbnk0","followers_url":"https://api.github.com/users/gbnk0/followers","following_url":"https://api.github.com/users/gbnk0/following{/other_user}","gists_url":"https://api.github.com/users/gbnk0/gists{/gist_id}","starred_url":"https://api.github.com/users/gbnk0/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gbnk0/subscriptions","organizations_url":"https://api.github.com/users/gbnk0/orgs","repos_url":"https://api.github.com/users/gbnk0/repos","events_url":"https://api.github.com/users/gbnk0/events{/privacy}","received_events_url":"https://api.github.com/users/gbnk0/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-01-31T13:45:08Z","updated_at":"2018-02-01T15:55:33Z","closed_at":"2018-02-01T15:55:33Z","author_association":"NONE","body":"Hello, sorry if this question was already answered:\r\n\r\nHow to add spend time / response time / client ip ... and maybe other custom fields to the sanic access log ?\r\n\r\nI tried with this:\r\n```python\r\ncustom_logger = logging.getLogger('sanic.access')\r\ncustom_logger.info('msg')\r\n```\r\n\r\nThanks,\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1103","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/events","html_url":"https://github.com/channelcat/sanic/issues/1103","id":292345018,"number":1103,"title":"How stable is Sanic? Can we consider it as at least beta?","user":{"login":"manisenkov","id":6490388,"avatar_url":"https://avatars0.githubusercontent.com/u/6490388?v=4","gravatar_id":"","url":"https://api.github.com/users/manisenkov","html_url":"https://github.com/manisenkov","followers_url":"https://api.github.com/users/manisenkov/followers","following_url":"https://api.github.com/users/manisenkov/following{/other_user}","gists_url":"https://api.github.com/users/manisenkov/gists{/gist_id}","starred_url":"https://api.github.com/users/manisenkov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/manisenkov/subscriptions","organizations_url":"https://api.github.com/users/manisenkov/orgs","repos_url":"https://api.github.com/users/manisenkov/repos","events_url":"https://api.github.com/users/manisenkov/events{/privacy}","received_events_url":"https://api.github.com/users/manisenkov/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-01-29T09:56:28Z","updated_at":"2018-02-02T21:21:55Z","closed_at":"2018-02-02T21:21:54Z","author_association":"CONTRIBUTOR","body":"How stable is Sanic now? Is there serious bugs or plans to drastically change API?\r\nCurrent status is [`Development Status :: 2 - Pre-Alpha`](https://github.com/channelcat/sanic/blob/9751a373439848548577203e34ca18d81e1509bb/setup.py#L46), maybe it's a time to change it to at least `Development Status :: 4 - Beta`?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1102","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/events","html_url":"https://github.com/channelcat/sanic/issues/1102","id":292189081,"number":1102,"title":"How to response 204 using response.json() ","user":{"login":"alaminopu","id":1296554,"avatar_url":"https://avatars2.githubusercontent.com/u/1296554?v=4","gravatar_id":"","url":"https://api.github.com/users/alaminopu","html_url":"https://github.com/alaminopu","followers_url":"https://api.github.com/users/alaminopu/followers","following_url":"https://api.github.com/users/alaminopu/following{/other_user}","gists_url":"https://api.github.com/users/alaminopu/gists{/gist_id}","starred_url":"https://api.github.com/users/alaminopu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alaminopu/subscriptions","organizations_url":"https://api.github.com/users/alaminopu/orgs","repos_url":"https://api.github.com/users/alaminopu/repos","events_url":"https://api.github.com/users/alaminopu/events{/privacy}","received_events_url":"https://api.github.com/users/alaminopu/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2018-01-28T08:53:05Z","updated_at":"2018-02-02T21:21:27Z","closed_at":"2018-02-02T21:21:27Z","author_association":"NONE","body":"Usually the `DELETE` request should return a [204](https://httpstatuses.com/204) response. How can I send 204 response using sanic. I was trying something like below. \r\n\r\n```python\r\nreturn response.json(\r\n        None,\r\n        status=204\r\n    )\r\n```\r\n\r\nBut it doesn't work, it response with null. \r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1099","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/events","html_url":"https://github.com/channelcat/sanic/issues/1099","id":291809694,"number":1099,"title":"How to achieve throttling?","user":{"login":"hustshawn","id":3147161,"avatar_url":"https://avatars0.githubusercontent.com/u/3147161?v=4","gravatar_id":"","url":"https://api.github.com/users/hustshawn","html_url":"https://github.com/hustshawn","followers_url":"https://api.github.com/users/hustshawn/followers","following_url":"https://api.github.com/users/hustshawn/following{/other_user}","gists_url":"https://api.github.com/users/hustshawn/gists{/gist_id}","starred_url":"https://api.github.com/users/hustshawn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hustshawn/subscriptions","organizations_url":"https://api.github.com/users/hustshawn/orgs","repos_url":"https://api.github.com/users/hustshawn/repos","events_url":"https://api.github.com/users/hustshawn/events{/privacy}","received_events_url":"https://api.github.com/users/hustshawn/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-01-26T06:22:37Z","updated_at":"2018-03-16T11:21:10Z","closed_at":"2018-01-26T21:52:44Z","author_association":"NONE","body":"I am using sanic to provide API service. But I need a throttling mechnism to control API access within a predefined limit. How can I achieve it?  I cannot find any related topic in the official document.","score":1.0}]}
0

